main/urls.py
from django.urls import path, re_path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    CakeView,
    CupcakeView,
    CheeseCakeView,
    FatayerView,
    ClientOrder,
    OrderDetail,
    ManakishView,
    MezeView,
    Privacy,
    Delivery,
    Profile,
    Generate,
    delete_model,
    increment,
    decrement,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    remove_from_order_page,
)

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cake/', CakeView.as_view(), name='cake'),
    path('cupcake/', CupcakeView.as_view(), name='cupcake'),
    path('cheesecake/', CheeseCakeView.as_view(), name='cheesecake'),
    path('fatayer/', FatayerView.as_view(), name='fatayer'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('manakish/', ManakishView.as_view(), name='manakish'),
    path('meze/', MezeView.as_view(), name='meze'),

    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),

    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-to-cart/<slug>/<price>/', add_to_cart, name='add-to-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('remove-item-from-cart/<int:slug>/<price>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('clientorder/', ClientOrder.as_view(), name="client-order"),
    path('order-detail/<int:pk>/', OrderDetail.as_view(), name="order-detail"),
    path('generate/', Generate.as_view(), name="generate"),
    path('remove_from_order_page/<int:pk>/',
         remove_from_order_page, name="remove_from_order_page"),
    path('privacy-policy/', Privacy.as_view(), name="privacy"),
    path('delivery-policy/', Delivery.as_view(), name="delivery_policy"),
    path('accounts/profile/', Profile.as_view(), name="profile"),
    path('delete/<pk>/', delete_model, name="delete_model"),
    path('increment/<pk>/', increment, name="increment"),
    path('decrement/<pk>/', decrement, name="decrement"),
]

webshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from main import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("password_reset", auth_views.PasswordResetView.as_view(template_name="account_reset_password"),
         name="password_reset"),
    path('', include('main.urls', namespace='main')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/clientorder.html
{% extends "base.html" %} {% block content %}
{% include "navbar0.html" %}
<main>
  <div class="container p-5 m-5" style="position: relative ; background-color: white; border-radius: 16px; left: 15%;">
    <a  href="{% url 'main:generate' %}" type="button" name="button" class="float-right btn btn-primary">Generate Invoice</a>

    <div class="table-responsive text-nowrap pt-5">
      <h2>Orders</h2>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col" class="h6">#</th>
            <th scope="col" class="h6">Name</th>
            <th scope="col" class="h6">Address</th>
            <th scope="col" class="h6">Ordered</th>
            <th scope="col" class="h6">Deliver</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <div class="bg-dark">
          <tr>
            <td class="h6">{{object.pk}}</td>
            <td class="h6"><a href="{% url 'main:order-detail' object.pk %}">{{ object.name }}</a></td>
            <td class="h6">{{ object.address }}</td>
            <td class="h6">{{ object.create }}</td>
            <td class="h6">{{ object.delivery }}</td>
            <td class="h6">
              <a
                style="color: red"
                href="{% url 'main:remove_from_order_page' object.pk %}"
              >
                <i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
        </div>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock content %}

templates/fatayer.html
{% extends "base.html" %} {% block content %}
{% load static %}
  {% include "navbar.html" %}
<main style="background-color:white">
  <div class="">
    <img class="bgimg" src="{% static 'img/fatayer1.jpg' %}" alt="" width="1090" height="220">
  </div>
  <div class="container-fluid marketing pt-1 mt-1">
   <h1 class="cap-text"style="font-family: 'Pacifico', cursive;">Fatayer</h1>
   <p class="text-muted" style="font-family: 'Prompt', sans-serif;"><a href="{% url 'main:home' %}" class="text-muted">Etusivu</a> &nbsp; /  &nbsp; Fatayer</p>
   <section class="text-center mt-1">
     <div class="row">
       {% for item in object_list %}
       {% if item.category == 'Fatayer' %}
       <div class="prod-card m-3">
         <div>
           <a href="{{ item.get_absolute_url }}">
           <div>
             <img src="{{ item.image1}}" class="mainimg" />
             <p class="p-2" style="font-family: 'Staatliches', cursive; text-transform: uppercase;margin:0; font-size:18px;">{{ item.name }}</p>
             <p class="" style=" text-transform: uppercase;margin-top:-10px; font-size:12px; color:gray;">&euro;{{ item.price }}</p>
           </div>
         </a>
         </div>
       </div>
       {%  endif %}
       {% endfor %}
     </div>
   </section>

    <!--Handling multiple pages-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page_obj.previous_page_number }}"
            aria-label="Previous"
          >
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Edellinen</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}"
            >{{ page_obj.number }}
            <span class="sr-only">(Nykyinen)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page_obj.next_page_number }}"
            aria-label="Next"
          >
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Seuraava</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
  </div>
  <br>
</main>

{% include "kissa.html" %}
{% endblock content %}

templates/footer.html
{% load static %}
<footer class="text-white footer" style="">
  <br><br><br><br><br><br>
    <dic class="container">
      <br>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">
            <img src="{% static 'img/brand_logo_2.svg' %}" alt="Untitled"  class="logo2">
            <div>
              <p class="foo-l" style="color:#BF9000; font-size:12px;">&copy;2021</p>
            </div>
            <br><br><br>
            <div class=" foo-l ">
              <div>
                <a class="fab fa-instagram fa-2x" style="color:#BF9000" href="https://www.instagram.com/maysamherkku/"></a>
                <a class="fab fa-facebook-f fa-2x px-5" style="color:#BF9000" href="https://www.facebook.com/maisaminherkkukotileipomoa/"></a>
                <a class="fab fa-youtube fa-2x pl-2" style="color:#BF9000" href="https://www.youtube.com/channel/UCw9o5p1ge-AivDbJafat5Bw"></a>
              </div>
            </div>
            <br>
          </div>
          <div class="col-md-2">
            <div>
              <p class=" foo-email" style="color:#BF9000; font-size:14px;"> <b>Verkkokauppa</b></p>
            </div>
            <div>
              <p style="color:#BF9000; font-size:10px;"><a style="color:#BF9000; font-size:12px;"  href="{% url 'main:home' %}">Etusivu</a></p>
            </div>
            <div>
              <p style="color:#BF9000; font-size:10px;"><a style="color:#BF9000; font-size:12px;"  href="{% url 'main:cake' %}">Kakut</a></p>
            </div>
            <div>
              <p style="color:#BF9000; font-size:10px;"><a style="color:#BF9000; font-size:12px;"  href="{% url 'main:cupcake' %}">Kuppikakut</a></p>
            </div>
            <div>
              <p style="color:#BF9000; font-size:10px;"><a style="color:#BF9000; font-size:12px;"  href="{% url 'main:cheesecake' %}">Juustokakut</a></p>
            </div>
            <div>
              <p style="color:#BF9000; font-size:10px;"><a style="color:#BF9000; font-size:12px;"  href="{% url 'main:fatayer' %}">Fatayer</a></p>
            </div>
            <div>
              <p style="color:#BF9000; font-size:10px;"><a style="color:#BF9000; font-size:12px;"  href="{% url 'main:manakish' %}">Manakish</a></p>
            </div>
            <div>
              <p style="color:#BF9000; font-size:10px;"><a style="color:#BF9000; font-size:12px;"  href="{% url 'main:meze' %}">Alkuruoat ja salaatit</a></p>
            </div>
          </div>
          <div class="col-md-3">
            <div>
              <p style="color:#BF9000; font-size:14px;"><b>MAISAMIN HERKKU</b></p>
            </div>
            <div>
              <p style="color:#BF9000; font-size:12px;">42100 Jämsä</p>
            </div>
            <div>
              <p class=" foo-email" style="color:#BF9000; font-size:12px;">Puh 040 5177444</p>
            </div>
            <div>
              <p class=" foo-email" style="color:#BF9000; font-size:12px;">info@maisaminherkku.fi</p>
            </div>
          </div>
          <div class="col-md-3">
            <div>
              <p class=" foo-email" style="color:#BF9000; font-size:14px;"><b> Info</b></p>
            </div>
            <div>
              <p class=" foo-email"> <a href="{% url 'main:privacy' %}"style="color:#BF9000; font-size:12px;">Tietosuojaseloste</a> </p>
            </div>
            <div>
              <p class=" foo-email"> <a href="{% url 'main:delivery_policy' %}"style="color:#BF9000; font-size:12px;">Toimitusehdot</a> </p>
            </div>
          </div>
        </div>
      </div>
      <br>
    </dic>
  </footer>

templates/home.html
{% extends "base.html" %} {% block content %}
{% load static %}
  {% include "navbar.html" %}
<main role="main">
    <div class="">
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="maimg"src="{% static 'img/home_2_1.jpg' %}" alt="">
          </div>
          <div class="carousel-item">
            <img class="maimg"src="{% static 'img/home_2_2.jpg' %}" alt="">
          </div>
          <div class="carousel-item">
            <img class="maimg"src="{% static 'img/home_2_3.jpg' %}" alt="">
          </div>
        </div>
      </div>
      <h1 class="maintext" style="color:#EEE">MAISAMIN <br /> &nbsp;&nbsp; <span style="position: relative;left: 40%; top: 10%;"> HERKKU </span></h1>

      <div class="spe-ord">
        <p class="" style="background-color:#d43817;padding:10px 5px;">Tee tilauksesi kolme päivää ennen!</p>
        <br>
        <br>
        <p class="">Erikoistilauksesta </p>
        <p class="">voit soittaa </p>
        <p class="">klo 9.00 -17.00</p>
        <p class="">Puh 040 5177444</p>
      </div>
    </div>
    <br />

    <div class="container marketing">
      <div class="row d-flex justify-content-center">

        <div class="col-lg-4">
          <br />
          <div class="par-1">
            <p class="par-1-head">Olen aina pitänyt käsillä tekemisestä !</p>
            <p>Tarinani alkoi, kun olin nuori tyttö ala-asteella piirtelemässä</p>
            <p>koulun seinille.</p>
            <p>Kasvaessani opin leipomaan, ja siitä tuli intohimoni.</p>
            <p>Aikanaan yliopistossa pyrin kirurgiksi, jotta voisin käyttää</p>
            <p>kädentaitojani parantamiseen.</p>
            <p>Vaikka tämä unelma ei ole vielä käynyt toteen, olen päässyt</p>
            <p>kauas kulinaarisella matkallani.</p>
            <p>Nyt Maisamin Herkulla tahdon jakaa kanssanne niitä</p>
            <p>aarteita, joita olen löytänyt matkan varrella.</p>
            <br>
            <h3>Hyvää ruokahalua!</h3>

          </div>
        </div>

      </div>
    </div>
        <hr class="featurette-divider">
        <div class="container-fluid">
          <div class="row featurette">
            <div class="col-md-7">
              <div class="dec-text">
                  <a href="{% url 'main:cake' %}">
                    <h2 class="par-text">Kakut</h2>
                  </a>
                  <div class="cake-par-text">
                  </div>

                <hr class="w-50">
                <br>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Täydellinen juhlakakku kaikkiin tilaisuuksiin</p>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Paras mitä voit testata</p>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Monia eri kerroksia</p>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Täynnä rakkautta</p>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Täynnä makuja</p>
              </div>
            </div>
            <div class="col-md-5">
              <img class="featurette-image img-fluid mx-auto" src="{% static 'img/home_5_1.jpg' %}" alt="Generic placeholder image">
            </div>
          </div>

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-7 order-md-2">
              <div class="dec-text">
                <a href="{% url 'main:cheesecake' %}">
                  <h2 class="par-text">Kermainen täyte ja keksipohja </h2>
                </a>
                <div class="chess-par-text">
                </div>
                <hr class="w-50">
                <br>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Kuka voi vastustaa tätä klassikkoa? Valitse perinteisistä hedelmä-, vanilja- tai pistaasijuustokakuista, tai luo oma makusi</p>
              </div>
            </div>
            <div class="col-md-5 order-md-1">
              <img class="featurette-image img-fluid mx-auto" src="{% static 'img/cheese3.jpg' %}" alt="Generic placeholder image">
            </div>
          </div>

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-7">
              <div class="dec-text">
                <div class="<div class="dec-text">
                  <a href="{% url 'main:cupcake' %}">
                    <h2 class="par-text">Kuppikakut</h2>
                  </a>
                  <div class="cupcake-par-text">
                  </div>
                  <hr class="w-50">
                  <br>
                  <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Nämä muffinsit näyttävät liian upeilta syötäviksi, mutta murusenkaan maistettuasi et malta lopettaa!</p>
                </div>
              </div>
            </div>
            <div class="col-md-5">
              <img class="featurette-image img-fluid mx-auto" src="{% static 'img/cupcake3.jpg' %}" alt="Generic placeholder image">
            </div>
          </div>

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-7 order-md-2">
              <div class="dec-text">
                <a href="{% url 'main:fatayer' %}">
                  <h2 class="par-text">Fatayer</h2>
                </a>
                <div class="fatayer-par-text">
                </div>
                <hr class="w-50">
                <br>
                <p class="h4 pl-2" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Leivonnainen, joka on täytetty lihalla, tai juustolla ja pinaatilla tai muilla täytteillä mielesi mukaan</p>
              </div>
            </div>
            <div class="col-md-5 order-md-1">
              <img class="featurette-image img-fluid mx-auto" src="{% static 'img/fatayer2.jpg' %}" alt="Generic placeholder image">
            </div>
          </div>

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-7">
              <div class="dec-text">
                <a href="{% url 'main:manakish' %}">
                  <h2 class="par-text">Manakish</h2>
                </a>
                <div class="manakish-par-text">
                </div>
                <hr class="w-50">
                <br>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Ohut taikina, jossa täytteinä za'atar mausteseosta ja jauhelihaa, tai juustoa ja selleriä tai muita täytteitä mielesi mukaan. </p>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Suosittu ruoka Levantin alueella.</p>
              </div>
            </div>
            <div class="col-md-5">
              <img class="featurette-image img-fluid mx-auto" src="{% static 'img/manakish3.jpg' %}" alt="Generic placeholder image">
            </div>
          </div>
            <hr class="featurette-divider">
          <div class="row featurette">
            <div class="col-md-7 order-md-2">
              <div class="dec-text">
                <a href="{% url 'main:meze' %}">
                  <h2 class="par-text">Alkuruoat ja salaatit</h2>
                </a>
                <div class="salaat-par-text">
                </div>
                <hr class="w-50">
                <br>
                <p class="h4" style="font-family: 'Aclonica', sans-serif;line-height:1.5; letter-spacing:0.1em;">Punaisista ja keltaisista kuorituista linsseistä tehty maukas, paksu keitto.
  Suosittu alku- ja pääruoka lähi-idän maissa.</p>
              </div>
            </div>
            <div class="col-md-5 order-md-1">
              <img class="featurette-image img-fluid mx-auto" src="{% static 'img/alk3.jpg' %}" alt="Generic placeholder image">
            </div>
          </div>
        </div>
        <br>
        <br>
        <br>
        <br>
</main>

{% endblock content %}

templates/kissa.html
{% load cart_template_tags %}
{% load static %}
<main>
  {% if user.is_authenticated %}
  {% if user|cart_item_count > 0 %}
    <a href="{% url 'main:order-summary' %}">
      <div class="kissa">
        <img class="" src="{% static 'img/kissa.svg' %}" alt="Generic placeholder image" width="70" height="70">
    </a>
  {% endif %}
  {% endif %}
</main>

templates/manakish.html
{% extends "base.html" %} {% block content %}
{% load static %}

  {% include "navbar.html" %}
<main style="background-color:white">
  <div class="">
    <img class="bgimg" src="{% static 'img/Manakish.jpg' %}" alt="" width="1090" height="220">

  </div>
  <div class="container-fluid marketing pt-1 mt-1">
    <h1 class="cap-text" style="font-family: 'Pacifico', cursive;">Manakish</h1>
    <p class="text-muted" style="font-family: 'Prompt', sans-serif;"><a href="{% url 'main:home' %}" class="text-muted">Etusivu</a> &nbsp; /  &nbsp; Manakish</p>
    <section class="text-center mt-1">
      <div class="row">
        {% for item in object_list %}
        {% if item.category == 'Manakish' %}
        <div class="prod-card m-3">
          <div>
            <a href="{{ item.get_absolute_url }}">
            <div>
              <img src="{{ item.image1}}" class="mainimg" />
              <p class="p-2" style="font-family: 'Staatliches', cursive; text-transform: uppercase;margin:0; font-size:18px;">{{ item.name }}</p>
              <p class="" style=" text-transform: uppercase;margin-top:-10px; font-size:12px; color:gray;">&euro;{{ item.price }}</p>
            </div>
          </a>
          </div>
        </div>
        {%  endif %}
        {% endfor %}
      </div>
    </section>

    <!--Handling multiple pages-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page_obj.previous_page_number }}"
            aria-label="Previous"
          >
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Edellinen</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}"
            >{{ page_obj.number }}
            <span class="sr-only">(Nykyinen)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page_obj.next_page_number }}"
            aria-label="Next"
          >
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Seuraava</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
  </div>
  <br>

</main>

{% include "kissa.html" %}
{% endblock content %}

templates/navbar0.html
{% load cart_template_tags %}
{% load static %}
{% load static i18n %}
<style media="screen">
  .text-dark{
    font-size: 18px;
  }
</style>
<nav class="navbar fixed-top navbar-expand-lg bg-white navbar-light sec-nav" style="background-color: rgb(253, 253, 253);" >


  <a class="logo" href="{% url 'main:home' %}">
    <img src="{% static 'img/brand_logo_1.svg' %}" alt="Untitled" style="position: relative; width: 100%;">
  </a>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav1"
    aria-controls="basicExampleNav1" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="basicExampleNav1">

  <ol class="navbar-nav">
    <li class="nav-item navico"><a class="text-dark" href="{% url 'main:home' %}">Etusivu</a></li>
    <li class="nav-item navico"><a class="text-dark" href="{% url 'main:cake' %}">Kakut</a></li>
    <li class="nav-item navico"><a class="text-dark" href="{% url 'main:cupcake' %}">Kuppikakut</a></li>
    <li class="nav-item navico"><a class="text-dark" href="{% url 'main:cheesecake' %}">Juustokakut</a></li>
    <li class="nav-item navico"><a class="text-dark" href="{% url 'main:fatayer' %}">Fatayer</a></li>
    <li class="nav-item navico"><a class="text-dark" href="{% url 'main:manakish' %}">Manakish</a></li>
    <li class="nav-item navico"><a class="text-dark" href="{% url 'main:meze' %}">Alkuruoat ja salaatit</a></li>
  </ol>
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      {% if user|cart_item_count > 0 %}
        <li class="nav-item navico" id="cart-row">
            <a href="{% url 'main:order-summary' %}"  class="text-dark" style="font-size:16px;">
              Ostoskori &nbsp;
              <span class="badge badge-pill black px-3 py-1 " style="background-color:#BF9000;color:white;" id="cart-count">{{ user|cart_item_count }}</span> &nbsp;
              <i class="fas fa-shopping-cart pl-1"></i>
            </a>
          </li>
        {% endif %}
        <li class="nav-item navico ">
          <a href="{% url 'main:profile' %}" class="text-dark" style="font-size:16px;">
          <i class="far fa-user-circle ">&nbsp; &nbsp;</i>Hei, {{ user }}</a>
        </li>
        <li class="nav-item navico">
          <a href="{% url 'account_logout' %}" class="text-dark" style="font-size:16px;">
            Kirjaudu ulos &nbsp; <i class="fas fa-sign-out-alt"></i>
          </a>
        </li>
        <li><br></li>
        {% if user.is_superuser %}
        <li class="nav-item navico">
            <a href="{% url 'main:client-order' %}" class="text-dark" style="font-size:16px;">
              Admin
            </a>
          </li>
        {% endif %}
      {% else %}
          <li class="nav-item navico">
            <a href="{% url 'account_signup' %}" style="font-size:16px;"
            class="text-dark"> Kirjaudu sisään </a>
          </li>
      {% endif %}
      <li></li>
      <br>
    </ul>
  </div>
</nav>

templates/order_snippet.html

<div class="" >
  <p class=" h4 mt-5 py-2" style="background-color:black; color:white; display:inline-block; padding:3px 30px; border-radius:3px;"><i class="fas fa-sign text-warning">
  </i> &nbsp;<b>Tee tilauksesi kolme päivää ennen</b>
  </p>
  <br><br><br>
  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted" style="font-family: 'Prompt', sans-serif;">Ostoskorisi</span>
    <span class="badge badge-danger badge-pill">{{ order.count }}</span>
  </h4>
  <ul class="list-group mb-3 z-depth-1" style="background-color:#DEDCE9">
    {% for order_item in order %}
    <li class="list-group-item d-flex justify-content-between lh-condensed" style="background-color:#DEDCE9">
      <div>
        <span class="text-muted ">
          {{ order_item.quantity }}  &nbsp;
        </span>
        <small class="text-muted pl-3"><i>{{ order_item.product}}</i></small>
        &nbsp;&nbsp;&nbsp;&nbsp;
        {% if order_item.is_gluteen_free %}
        <br>
        <span class="pl-5 text-muted" style="font-size:10px;">Gluteeniton</span>
        {% endif %}
        &nbsp;
        {% if order_item.is_loctose_free %}
        <br>
        <span class="pl-5 text-muted" style="font-size:10px;">Laktoositon</span>
        {% endif %}
        &nbsp;
        {% if order_item.additional_info %}
        <span class="addinfo">A</span>
        {% endif %}
      </div>
      <span class="text-muted h6" style="font-family: 'Prompt', sans-serif;">{{ order_item.get_final_price }} &euro;</span>
    </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between mt-2" style="background-color:#DEDCE9">
      <span class="h5" style="font-family: 'Prompt', sans-serif;">Yhteensä</span>
      <strong class="order_sum_tot h5" >&nbsp;{{ object }}  &euro;</strong>
    </li>
  </ul>
</div>